[platformio]
default_envs = onebin

[env]
platform = espressif32
board = m5stack-stamps3
framework = arduino
monitor_speed = 115200
upload_speed = 1500000
lib_deps =
  m5stack/M5Cardputer @ ^1.0.3
build_flags =
  -std=gnu++17
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DCORE_DEBUG_LEVEL=3

[env:cardputer]
build_flags =
  ${env.build_flags}
  -DWALKIETALKIE_BOARD_VARIANT=BOARD_VARIANT_CARDPUTER

[env:cardputer_adv]
build_flags =
  ${env.build_flags}
  -DWALKIETALKIE_BOARD_VARIANT=BOARD_VARIANT_CARDPUTER_ADV

[env:onebin]
lib_deps =
  ${env.lib_deps}
build_flags =
  ${env.build_flags}
