#!/usr/bin/env python3

from __future__ import annotations

import argparse
import subprocess
import tempfile
from pathlib import Path


MESSAGES = [
    ("ok", "OK"),
    ("call_me", "Call me"),
    ("busy", "Busy"),
    ("where_are_you", "Where are you?"),
    ("come_here", "Come here"),
    ("test", "Test"),
    ("need_help", "Need help"),
    ("on_my_way", "On my way"),
    ("repeat", "Repeat"),
]

SAMPLE_RATE_HZ = 8000
FRAME_DURATION_MS = 10
FRAME_BYTES = (SAMPLE_RATE_HZ * FRAME_DURATION_MS) // 1000
SILENCE_BYTE = 0x80
FFMPEG_FILTER = (
    "highpass=f=120,"
    "lowpass=f=3400,"
    "silenceremove=start_periods=1:start_silence=0.03:start_threshold=-40dB:"
    "stop_periods=-1:stop_silence=0.08:stop_threshold=-40dB,"
    "volume=4dB"
)


def run(cmd: list[str]) -> None:
    subprocess.run(cmd, check=True)


def synthesize_clip(text: str, wav_path: Path, raw_path: Path, voice: str, speed: int) -> bytes:
    run(["espeak-ng", "-w", str(wav_path), "-s", str(speed), "-v", voice, text])
    run(
        [
            "ffmpeg",
            "-v",
            "error",
            "-i",
            str(wav_path),
            "-af",
            FFMPEG_FILTER,
            "-ac",
            "1",
            "-ar",
            str(SAMPLE_RATE_HZ),
            "-f",
            "u8",
            "-y",
            str(raw_path),
        ]
    )
    data = raw_path.read_bytes()
    remainder = len(data) % FRAME_BYTES
    if remainder:
        data += bytes([SILENCE_BYTE]) * (FRAME_BYTES - remainder)
    return data


def render_array(data: bytes) -> str:
    lines = []
    for offset in range(0, len(data), 12):
        chunk = ", ".join(f"0x{byte:02X}" for byte in data[offset : offset + 12])
        lines.append(f"    {chunk},")
    return "\n".join(lines)


def render_source(clips: list[tuple[str, str, bytes]]) -> str:
    arrays = []
    table_entries = []
    for index, (slug, text, data) in enumerate(clips):
        arrays.append(
            "\n".join(
                [
                    f"const uint8_t kQuickMessageClip{index}[] PROGMEM = {{",
                    render_array(data),
                    "};",
                    "",
                ]
            )
        )
        table_entries.append(
            f'    {{kQuickMessageClip{index}, sizeof(kQuickMessageClip{index}), {SAMPLE_RATE_HZ}, {FRAME_DURATION_MS}}},  // {text}'
        )

    return "\n".join(
        [
            "// Generated by tools/generate_quick_message_clips.py",
            '#include "QuickMessageClips.h"',
            "",
            "#include <Arduino.h>",
            "",
            "namespace wt {",
            "",
            "namespace {",
            "",
            *arrays,
            "constexpr QuickMessageClip kQuickMessageClips[] = {",
            *table_entries,
            "};",
            "",
            "static_assert(sizeof(kQuickMessageClips) / sizeof(kQuickMessageClips[0]) == config::kMaxQuickMessages,",
            '              "Quick message clip table must match the preset table.");',
            "",
            "}  // namespace",
            "",
            "const QuickMessageClip* quickMessageClip(uint8_t index) {",
            "  if (index >= quickMessageClipCount()) {",
            "    return nullptr;",
            "  }",
            "  return &kQuickMessageClips[index];",
            "}",
            "",
            "uint8_t quickMessageClipCount() {",
            "  return static_cast<uint8_t>(sizeof(kQuickMessageClips) / sizeof(kQuickMessageClips[0]));",
            "}",
            "",
            "}  // namespace wt",
            "",
        ]
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate bundled quick-message voice clips.")
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("src/QuickMessageClips.cpp"),
        help="Output C++ source file.",
    )
    parser.add_argument("--voice", default="en-us", help="espeak-ng voice name.")
    parser.add_argument("--speed", default=155, type=int, help="espeak-ng speech speed.")
    args = parser.parse_args()

    output = args.output.resolve()
    output.parent.mkdir(parents=True, exist_ok=True)

    clips: list[tuple[str, str, bytes]] = []
    with tempfile.TemporaryDirectory(prefix="cardie-talkie-tts-") as temp_dir_name:
        temp_dir = Path(temp_dir_name)
        for slug, text in MESSAGES:
            wav_path = temp_dir / f"{slug}.wav"
            raw_path = temp_dir / f"{slug}.u8"
            clips.append((slug, text, synthesize_clip(text, wav_path, raw_path, args.voice, args.speed)))

    output.write_text(render_source(clips), encoding="ascii")
    print(f"Generated {output}")


if __name__ == "__main__":
    main()
